---
name: local-lib-profiles
version: 0.05
author:
  - 'Christopher Mckay <potatohead@potatolan.com>'
abstract: makes modules feel at home
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  File::Util: 0
  Params::Validate: 0
  autodie: 0
  local::lib: 0
configure_requires:
  Module::Build: 0.35
provides:
  local::lib::profiles:
    file: lib/local/lib/profiles.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
